In [1]:
# Download Example Files


--2021-06-14 06:22:18--  https://dl.dropboxusercontent.com/s/gl1joi8ntv9rn4i/eg3.csv?dl=0
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.5.15, 2620:100:601d:15::a27d:50f
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.5.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44 [text/csv]
Saving to: ‘/content/eg.csv’

/content/eg.csv     100%[===================>]      44  --.-KB/s    in 0s      

2021-06-14 06:22:18 (7.16 MB/s) - ‘/content/eg.csv’ saved [44/44]

--2021-06-14 06:22:18--  https://dl.dropboxusercontent.com/s/bramigg8l9sboy5/Simplified_Houses.csv?dl=0
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.5.15, 2620:100:601d:15::a27d:50f
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.5.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 947327 (925K) [text/csv]
Saving to: ‘/content/Houses.csv’

/content/Houses.csv 100%[====

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('eg.csv')

In [8]:
df.head(3)

x1  x2   y
0   1   7  57
1   3   4  46
2   5   3  49

In [9]:
import numpy as np

In [10]:
x = np.array([1,2,3,4])

In [12]:
x.shape

(4,)

In [13]:
# Obj: Create 2 arrays: Feature.. Label
df.head()

x1  x2   y
0   1   7  57
1   3   4  46
2   5   3  49
3   7   2  52

In [15]:
features = ["x1", "x2"]
feature_arr = df[features].values

label_arr = df["y"].values

In [17]:
label_arr.shape

(4,)

In [18]:
feature_arr

array([[1, 7],
       [3, 4],
       [5, 3],
       [7, 2]])

In [19]:
feature_arr.shape

(4, 2)

In [20]:
df = pd.read_csv('Houses.csv')

In [21]:
df.head()

House_Age   Rooms  Bedrooms  Population  Households  Income  House_Price
0       41.0   880.0     129.0       322.0       126.0  8.3252     452600.0
1       21.0  7099.0    1106.0      2401.0      1138.0  8.3014     358500.0
2       52.0  1467.0     190.0       496.0       177.0  7.2574     352100.0
3       52.0  1274.0     235.0       558.0       219.0  5.6431     341300.0
4       52.0  1627.0     280.0       565.0       259.0  3.8462     342200.0

In [22]:
feature = ['House_Age', 'Rooms', 'Bedrooms','Population', 'Households', 'Income']
feature_arr = df[feature].values

In [23]:
feature_arr

array([[4.1000e+01, 8.8000e+02, 1.2900e+02, 3.2200e+02, 1.2600e+02,
        8.3252e+00],
       [2.1000e+01, 7.0990e+03, 1.1060e+03, 2.4010e+03, 1.1380e+03,
        8.3014e+00],
       [5.2000e+01, 1.4670e+03, 1.9000e+02, 4.9600e+02, 1.7700e+02,
        7.2574e+00],
       ...,
       [1.7000e+01, 2.2540e+03, 4.8500e+02, 1.0070e+03, 4.3300e+02,
        1.7000e+00],
       [1.8000e+01, 1.8600e+03, 4.0900e+02, 7.4100e+02, 3.4900e+02,
        1.8672e+00],
       [1.6000e+01, 2.7850e+03, 6.1600e+02, 1.3870e+03, 5.3000e+02,
        2.3886e+00]])

In [24]:
feature_arr.shape

(20433, 6)

In [25]:
label_arr = df["House_Price"].values

In [26]:
label_arr

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

In [27]:
label_arr.shape

(20433,)

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
model = LinearRegression()
model.fit(feature_arr, label_arr)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [39]:
house_age = 21
rooms = 997
bedrooms = 180
population = 320
households = 98
income = 4.563
 
pred_features = [[house_age, rooms, bedrooms, population, households, income]]

In [40]:
x = model.predict(pred_features)[0]

print(f'Your house is worth ${int(x//1000)}K')

Your house is worth $210K


In [37]:
model.coef_

array([ 1.88212143e+03, -1.97331147e+01,  1.00943796e+02, -3.53190219e+01,
        1.24803173e+02,  4.77483808e+04])

In [38]:
model.intercept_

-46139.647308358195