In [ ]:
import numpy as np

In [ ]:
x_li = [1,2,3,4,5,6]
print(x_li)

[1, 2, 3, 4, 5, 6]


In [ ]:
len(x_li)

6

In [ ]:
x_np = np.array([1,2,3,4,5,6])
print(x_np)

[1 2 3 4 5 6]


In [ ]:
x_np.shape

(6,)

(6) => (3,2)  => (3,1,2)


In [ ]:
# 'five', 'six' is in the 1st dimension
# 'one', 'two' is in the 2nd dimension
# 'three', 'four' is in the 3rd dimension


[first dim 'five', 'six'  [second dim 'one', 'two'  [third dimension  'three', 'four']  ] ]

In [ ]:
[1st dim [2nd dim] [2nd dim] ]

In [ ]:
x_np1 = np.array([ [1,2],  [3,4], [5,6] ])

> 1st Dimension 

shape: (3,) because we got 3 elements in our first dimension

1.   1st elem: [1,2]
2.   2nd elem: [3,4]
3.   3rd elem: [5,6]


> 2nd Dimension

shape: (,2), because we got 2 elements in the 2nd dimension

first 2nd dim occurance: [1,2]
1.  1st elem: 1
2.  2nd elem: 2

second 2nd dim occurance: [3,4]
1.  1st elem: 3
2.  2nd elem: 4

Thrid 2nd dim occurance: [5,6]
1.  1st elem: 5
2.  2nd elem: 6


In [ ]:
x_np1.shape

(3, 2)

In [72]:
# This 

np1 = np.array([
 [1,2],
 [3,4],
 [5,6]
])
print(np1.shape)

(3, 2)


In [73]:
np2 = np.array([
 [ [1] ,[2] ],
 [ [3] ,[4] ],
 [ [5] ,[6] ]
])
print(np2.shape)

(3, 2, 1)


In [ ]:
x_np = np.array([1,2,3,4,5,6])
print(x_np.shape)

(6,)


In [ ]:
x_np.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
x = np.array([ [1], [2], [3], [4]])
y = np.array([3,5,7,9])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
# Initialize the model to use the LinearRegression algorithm
model = LinearRegression()

In [75]:
# Train the model
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
# Get the learnt weights
model.coef_

array([2.])

In [ ]:
# Get the learnt bias
model.intercept_

1.0

In [76]:
#Make predictions. Since the x array is 2d and of shape (num_egs, 1) so when i do prediction (with 2 egs) I should pass in a 2d array of shape (2,1)
my = np.array([[20], [30]])
model.predict(my)

array([41., 61.])

In [77]:
x = np.array([  [1,7], [3,4], [5,3], [7,2]])
y = np.array([57, 46, 49, 52])

In [78]:
model = LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.coef_

array([5., 7.])

In [ ]:
model.intercept_

3.0

In [ ]:
model.predict([[2,3]])

array([34.])

In [ ]:
!wget https://dl.dropboxusercontent.com/s/gl1joi8ntv9rn4i/eg3.csv?dl=0 -O /content/eg3.csv

--2020-10-05 07:49:52--  https://dl.dropboxusercontent.com/s/gl1joi8ntv9rn4i/eg3.csv?dl=0
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.82.15, 2620:100:6032:15::a27d:520f
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.82.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44 [text/csv]
Saving to: ‘/content/eg3.csv’

/content/eg3.csv    100%[===================>]      44  --.-KB/s    in 0s      

2020-10-05 07:49:53 (6.16 MB/s) - ‘/content/eg3.csv’ saved [44/44]



In [ ]:
import pandas as pd

In [ ]:
# Get pandas Dataframe from the csv file
df = pd.read_csv('eg3.csv')

In [ ]:
df.head()

x1  x2   y
0   1   7  57
1   3   4  46
2   5   3  49
3   7   2  52

In [ ]:
#Same index operations as a dictionary

x = df[['x1', 'x2']]
y = df['y']

In [ ]:
x = np.array(x)
y = np.array(y)

In [ ]:
model = LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
!wget https://dl.dropboxusercontent.com/s/q47f19m0y680v6f/boston.csv?dl=0 -O /content/boston.csv

--2020-10-05 07:57:04--  https://dl.dropboxusercontent.com/s/q47f19m0y680v6f/boston.csv?dl=0
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.82.15, 2620:100:6032:15::a27d:520f
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.82.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35203 (34K) [text/csv]
Saving to: ‘/content/boston.csv’

/content/boston.csv 100%[===================>]  34.38K  --.-KB/s    in 0.01s   

2020-10-05 07:57:05 (2.37 MB/s) - ‘/content/boston.csv’ saved [35203/35203]



In [ ]:
df = pd.read_csv('boston.csv')

In [ ]:
df.head(10)

CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33   36.2
5  0.02985   0.0   2.18     0  0.458  ...  222     18.7  394.12   5.21   28.7
6  0.08829  12.5   7.87     0  0.524  ...  311     15.2  395.60  12.43   22.9
7  0.14455  12.5   7.87     0  0.524  ...  311     15.2  396.90  19.15   27.1
8  0.21124  12.5   7.87     0  0.524  ...  311     15.2  386.63  29.93   16.5
9  0.17004  12.5   7.87     0  0.524  ...  311     15.2  386.71  17.10   18.9

[10 rows x 14 columns]

In [ ]:
y = df.pop('Price').values

In [ ]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD  TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31     0  0.538  ...    1  296     15.3  396.90   4.98
1  0.02731   0.0   7.07     0  0.469  ...    2  242     17.8  396.90   9.14
2  0.02729   0.0   7.07     0  0.469  ...    2  242     17.8  392.83   4.03
3  0.03237   0.0   2.18     0  0.458  ...    3  222     18.7  394.63   2.94
4  0.06905   0.0   2.18     0  0.458  ...    3  222     18.7  396.90   5.33

[5 rows x 13 columns]

In [ ]:
x = df.values

In [ ]:
x.shape

(506, 13)

In [ ]:
y.shape

(506,)

In [ ]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
my = x[34]

In [ ]:
my.shape

(13,)

We need the shape to be (1,13)

In [ ]:
print(my)

[  1.61282   0.        8.14      0.        0.538     6.096    96.9
   3.7598    4.      307.       21.      248.31     20.34   ]


In [ ]:
model.predict([my])

array([13.70675891])