In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
#Corpus
texts =  ['It is a sunny today', 'It is rainy today', 'I hope it is not raining now']

In [11]:
tokenizer = Tokenizer()

In [12]:
#Learn the vocabulary from the corpus
#This vocabulary will be used for vectorization (Convert text to integers)
tokenizer.fit_on_texts(texts)

In [13]:
print(tokenizer.word_index)

{'it': 1, 'is': 2, 'today': 3, 'a': 4, 'sunny': 5, 'rainy': 6, 'i': 7, 'hope': 8, 'not': 9, 'raining': 10, 'now': 11}


In [18]:
new = 'It is neither sunny nor rainy today'

In [19]:
#Vectorize the new sentence
tokenizer.texts_to_sequences([new])

[[1, 2, 5, 6, 3]]

In [20]:
texts = [
         'Use the tokenizer to fit the following text',
         'tokenizer will first fit on the text and then be used to transform other text',
         'fitting a tokenizer is not the same as fitting a model. One is used for preprocessing and one is used for training different'
]
 
new = ['the tokenizer and the model are different after all']

In [22]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

In [25]:
print(tokenizer.word_index)

{'the': 1, 'tokenizer': 2, 'text': 3, 'used': 4, 'is': 5, 'to': 6, 'fit': 7, 'and': 8, 'fitting': 9, 'a': 10, 'one': 11, 'for': 12, 'use': 13, 'following': 14, 'will': 15, 'first': 16, 'on': 17, 'then': 18, 'be': 19, 'transform': 20, 'other': 21, 'not': 22, 'same': 23, 'as': 24, 'model': 25, 'preprocessing': 26, 'training': 27, 'different': 28}


In [23]:
tokenizer.texts_to_sequences(new)

[[1, 2, 8, 1, 25, 28]]

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
texts =  ['It is a sunny today', 'It is rainy today', 'I hope it is not raining now']

In [28]:
vect = CountVectorizer()

In [29]:
# Use fit instead of fit_on_texts
vect.fit(texts)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [30]:
# Use vocabulary_ instead of word_index
vect.vocabulary_

{'hope': 0,
 'is': 1,
 'it': 2,
 'not': 3,
 'now': 4,
 'raining': 5,
 'rainy': 6,
 'sunny': 7,
 'today': 8}

In [35]:
new = ['It is neither sunny nor rainy today but it was sunny yesterday']

In [36]:
# Use transform instead of texts_to_sequences
vect.transform(new).toarray()

array([[0, 1, 2, 0, 0, 0, 1, 2, 1]])

In [37]:
corpus = [
          'This word will appear once only',
          'the number five is a common occurrence',
]
 
new = ['By doing word word word word the occurrence of word will be five']

In [38]:
vect = CountVectorizer()

vect.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [45]:
vect.vocabulary_

{'appear': 0,
 'common': 1,
 'five': 2,
 'is': 3,
 'number': 4,
 'occurrence': 5,
 'once': 6,
 'only': 7,
 'the': 8,
 'this': 9,
 'will': 10,
 'word': 11}

In [47]:
vect.transform(new).toarray()

array([[0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 5]])

In [48]:
!wget https://dl.dropboxusercontent.com/s/79wcs0ycktiz5uz/Disaster_train.csv?dl=0 -O /content/train.csv

--2020-10-08 06:41:27--  https://dl.dropboxusercontent.com/s/79wcs0ycktiz5uz/Disaster_train.csv?dl=0
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.5.15, 2620:100:601f:15::a27d:90f
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.5.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 987712 (965K) [text/csv]
Saving to: ‘/content/train.csv’

/content/train.csv  100%[===================>] 964.56K  --.-KB/s    in 0.1s    

2020-10-08 06:41:28 (6.72 MB/s) - ‘/content/train.csv’ saved [987712/987712]



In [49]:
import pandas as pd

In [50]:
df = pd.read_csv('train.csv')

In [51]:
df.head()

id keyword  ...                                               text target
0   1     NaN  ...  Our Deeds are the Reason of this #earthquake M...      1
1   4     NaN  ...             Forest fire near La Ronge Sask. Canada      1
2   5     NaN  ...  All residents asked to 'shelter in place' are ...      1
3   6     NaN  ...  13,000 people receive #wildfires evacuation or...      1
4   7     NaN  ...  Just got sent this photo from Ruby #Alaska as ...      1

[5 rows x 5 columns]

In [52]:
#Index out the sentences
x = df['text'].values
#Index out the labels: 1 for disaster and 0 for no disaster
y = df['target'].values

In [78]:
print(x)

['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'
 'Forest fire near La Ronge Sask. Canada'
 "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected"
 ... 'M1.94 [01:04 UTC]?5km S of Volcano Hawaii. http://t.co/zDtoyd8EbJ'
 'Police investigating after an e-bike collided with a car in Little Portugal. E-bike rider suffered serious non-life threatening injuries.'
 'The Latest: More Homes Razed by Northern California Wildfire - ABC News http://t.co/YmY4rSkQ3d']


In [82]:
print(y[:20])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]


In [61]:
#Initialize the count vectorizer
vect = CountVectorizer()
#Fit the count vectorizer on all the sentences so you can learn a vocabulary
vect.fit(x)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [62]:
#Sparse matrix is faster
x_vect = vect.transform(x)

In [69]:
type(x_vect)

scipy.sparse.csr.csr_matrix

In [67]:
x_np = vect.transform(x).toarray()

In [70]:
x_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [71]:
from sklearn.linear_model import LogisticRegression

In [72]:
model = LogisticRegression()

model.fit(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [77]:
my = 'There is a forest fire'

#Perform the same preprocessing (vectorization) on my
my_vect = vect.transform([my])
model.predict(my_vect)

array([1])

In [84]:
model_1 = LogisticRegression(C=1)
model_10 = LogisticRegression(C=10)

In [85]:
model_1.fit(x_vect, y)
model_1.score(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9675554971758834

In [86]:
model_10.fit(x_vect, y)
model_10.score(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9963220806515172

In [87]:
model_2 = LogisticRegression(C=5, solver='liblinear', max_iter=500)

In [89]:
model_s1 = LogisticRegression(solver='newton-cg')
model_s1.fit(x_vect, y)
model_s1.score(x_vect, y)

0.9675554971758834

In [90]:
model_s2 = LogisticRegression(solver='lbfgs')
model_s2.fit(x_vect, y)
model_s2.score(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9675554971758834

In [91]:
model_s3 = LogisticRegression(solver='liblinear')
model_s3.fit(x_vect, y)
model_s3.score(x_vect, y)

0.967818205700775

In [93]:
model_s4 = LogisticRegression(solver='sag')
model_s4.fit(x_vect, y)
model_s4.score(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


0.9670300801261001

In [94]:
model_s5 = LogisticRegression(solver='saga')
model_s5.fit(x_vect, y)
model_s5.score(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


0.9621699724156049

In [114]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [96]:
params = {
    'C':[10,50,100],
    'solver':['liblinear', 'sag'],
    'max_iter':[100,250,500]
}

In [97]:
model_search = LogisticRegression()

In [98]:
grid = GridSearchCV(model_search, params)

In [ ]:
#RandomSearchCV

In [99]:
grid.fit(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the 

GridSearchCV(cv=None, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [10, 50, 100], 'max_iter': [100, 250, 500],
                         'solver': ['liblinear', 'sag']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [100]:
grid.best_params_

{'C': 10, 'max_iter': 100, 'solver': 'liblinear'}

In [102]:
model_best = grid.best_estimator_

In [103]:
print(model_best)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)


In [104]:
model = LogisticRegression()
model.fit(x_vect, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [105]:
#My custom sentence
my = ['Hurricane hits the road']
#Vectorizing my sentence so it becomes a set of numbers (Which can be used for making predictions)
my_vect = vect.transform(my)

#No tuning
print(model.predict(my_vect))
#Have tuning
print(model_best.predict(my_vect))

[0]
[1]


In [108]:
my = input('Sentence:')
my_vect = vect.transform([my])

preds = model_best.predict(my_vect)[0]

if preds == 0:
  print('Not a disaster!')
elif preds == 1:
  print('Is a disaster')

Sentence:i like candy
Not a disaster!


In [109]:
my = 'It rained rained yesterday'
my_vect = vect.transform([my]).toarray()

In [111]:
print(my_vect)

[[0 0 0 ... 0 0 0]]


In [113]:
len(vect.vocabulary_)

21637

In [110]:
my_vect.shape

(1, 21637)